export const WHEEL_PICKER_OPTIONS = {
  DEFAULT_ITEM_HEIGHT: 60,
  DEFAULT_START_RANGE_INDEX_AGE: 15,
  DEFAULT_END_RANGE_INDEX_AGE: 90,
  DEFAULT_START_RANGE_INDEX_HEIGHT: 140,
  DEFAULT_END_RANGE_INDEX_HEIGHT: 240,
};
